### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-includepatriciamartinez#2]
Muy buen trabajo!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 224 / 347
- [x] CARPETAS > CSS: La ruta del fichero CSS debe empezar por `./styles/` o `./css/`.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: Necesitamos al menos una etiqueta `h1`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > COLOR: El color del h1 debe ser blanco
- [x] CSS > COLOR: El color de los enlaces debe ser  4a4a4a
- [x] CSS > FONT-FAMILY: Es recomendable que la fuente del body sea Rubik para aprovechar la herencia.
- [x] CSS > FONT-FAMILY: La fuente del h1 debe ser Rubik
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > HEIGHT: El `main` debe ocupar todo el alto de la página.
- [x] CSS > FIXED: La cabecera debe estar fija en la parte superior de la página y con `top: 0`.
- [x] CSS > FIXED: La cabecera debe medir todo el ancho de la página.
- [x] CSS > FLEX: El texto Creando diversidad digital debe estar centrado horizontal y verticalmente, lo mejor es hacerlo con flex.
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

**Comment by includepatriciamartinez** [comment]
Hola Miguel,
Creo que ya he solucionado todos los issues que que tenía pendiente. Espero haber hecho pleno.
Le he cogido el gusto a esto de programar, ya voy camino de hacer "click" y no el "crack".
Nos vemos el miércoles. Gracias por todo :)
